### ISSUE TITLE
6 player mod

### ISSUE THREAD

**Issue by hello-lab** [olegyadrov/TheFriendlyGhost#1]
can you make a 6 player mod for phasmophobia since it is now in il2cpp and the previous server mod was in mono

**Comment by olegyadrov** [comment]
I was able to increase the maximum amount of players in my lobby, but nobody was able to join. I suspect that the client checks the capacity of the lobby and if it detects that the amount is different from 4, it disconnects. So, in order to play with more than 4 players, you would also need to patch every client.

**Comment by hello-lab** [comment]
> I was able to increase the maximum amount of players in my lobby, but nobody was able to join. I suspect that the client checks the capacity of the lobby and if it detects that the amount is different from 4, it disconnects. So, in order to play with more than 4 players, you would also need to patch every client.

can you give me the patch then
for 0.5.01
